server:
  transport: http
  port: 8089
  host: "0.0.0.0"
  ssl_keyfile: ./certs/key.pem
  ssl_certfile: ./certs/cert.pem

tools:
  - path: flux_mcp.job.flux_handle_delegation
  - path: flux_mcp.job.flux_submit_job
  - path: flux_mcp.job.flux_cancel_job
  - path: flux_mcp.job.flux_get_job_info

# prompts:
#  - path: hpc_mcp.t.build.docker.docker_build_persona_prompt
#    name: build_expert
